spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webdesign?useUnicode=true&characterEncoding=utf-8

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.group.webdesign_back.pojo

server:
  port: 9090

pagehelper:
  helper-dialect: mysql
  #  分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页，pageNum>pages(超过总数时)，
  #  会查询最后一页。默认false 时，直接根据参数进行查询
  reasonable: true
  #  支持通过 Mapper 接口参数来传递分页参数
  support-methods-arguments: true
  #  增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable
  params: count=countSql
